package einoapp

// Graph describes the workflow node topology used by the local agent runtime.
// It is intentionally metadata-only: nodes may propose effects, but execution still
// goes through the local ToolRouter, policy engine, approval center, and executor.
type Graph struct {
	Name  string      `json:"name"`
	Nodes []GraphNode `json:"nodes"`
	Edges []GraphEdge `json:"edges"`
}

// GraphNode is a named workflow stage.
type GraphNode struct {
	ID          string `json:"id"`
	Description string `json:"description,omitempty"`
}

// GraphEdge documents an allowed transition between workflow stages.
type GraphEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// NewAgentGraph returns the default single-tool HITL graph for the MVP workflow.
func NewAgentGraph() Graph {
	nodes := []GraphNode{
		{ID: "BuildContextNode", Description: "loads conversation, memory, knowledge, and tool catalog context"},
		{ID: "PlanNode", Description: "produces a direct-answer plan or a structured tool proposal"},
		{ID: "ToolProposalNode", Description: "captures the immutable tool proposal generated by the planner"},
		{ID: "EffectInferenceNode", Description: "derives effects, risk, sensitivity, and confidence"},
		{ID: "PolicyDecisionNode", Description: "decides auto execution or approval"},
		{ID: "ApprovalInterruptNode", Description: "stores approval snapshot and pauses the run"},
		{ID: "ExecuteToolNode", Description: "executes an auto-approved proposal or approved snapshot"},
		{ID: "SummarizeNode", Description: "persists assistant output from model or tool result"},
		{ID: "PersistNode", Description: "records messages, usage, run state, and events"},
	}
	edges := []GraphEdge{
		{From: "BuildContextNode", To: "PlanNode"},
		{From: "PlanNode", To: "ToolProposalNode"},
		{From: "PlanNode", To: "SummarizeNode"},
		{From: "ToolProposalNode", To: "EffectInferenceNode"},
		{From: "EffectInferenceNode", To: "PolicyDecisionNode"},
		{From: "PolicyDecisionNode", To: "ApprovalInterruptNode"},
		{From: "PolicyDecisionNode", To: "ExecuteToolNode"},
		{From: "ApprovalInterruptNode", To: "ExecuteToolNode"},
		{From: "ExecuteToolNode", To: "SummarizeNode"},
		{From: "SummarizeNode", To: "PersistNode"},
	}
	return Graph{Name: "local-agent-hitl-workflow", Nodes: nodes, Edges: edges}
}
